name: API CI - Testes e Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar o código do repositório
      uses: actions/checkout@v4

    - name: Configurar o Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Instalar as dependências do projeto
      run: npm install

    - name: Compilar o TypeScript (Build)
      run: npm run build

    - name: Executar todos os testes (Jest)
      run: npm run test